version: "3"

services:
  app:
    image: openjdk:8
    volumes:
    - ./target:/usr/app
    working_dir: /usr/app
    command: java -jar sample-payment-service-0.1.0.jar --spring.data.mongodb.host=mongo
    links:
    - mongo
    container_name: "sample_api_service"
    ports:
    - "8080:8080"

  mongo:
    image: "mongo:latest"
